apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercenter-rpc
  namespace: go-zero-for-k8s
  labels:
    app: usercenter-rpc
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: usercenter-rpc
  template:
    metadata:
      labels:
        app: usercenter-rpc
    spec:
      serviceAccountName: find-endpoints
      containers:
      - name: usercenter-rpc
        image: usercenter-rpc:v1.0
        ports:
        - containerPort: 8989
        readinessProbe:
          tcpSocket:
            port: 8989
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8989
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 200m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 100Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: usercenter-rpc-svc
  namespace: go-zero-for-k8s
spec:
  ports:
  - port: 8989
    targetPort: 8989
  selector:
    app: usercenter-rpc

---

#apiVersion: autoscaling/v2beta2
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usercenter-rpc-hpa-c
  namespace: go-zero-for-k8s
  labels:
    app: usercenter-rpc-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usercenter-rpc
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

#apiVersion: autoscaling/v2beta2
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usercenter-rpc-hpa-m
  namespace: go-zero-for-k8s
  labels:
    app: usercenter-rpc-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usercenter-rpc
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
